exe: new FlagSet instance for each executed command
As of 33ae962, subsequent calls to a command like 'new' reused
a FlagSet. This is not so noticable in sequential calls, but in
the parallel calls in e1e resulted in this:

  --- FAIL: TestSCPWorks (12.12s)
      infra_test.go:862: want "Creating .*e1e-4575-testscpworks" match in output (read |0: i/o timeout). actual output:
           ← current

          exe.dev ▶ new --name=e1e-4575-testscpworks
          Creating e1e-4575-testsshworks (medium) using image boldsoftware/exeuntu...
  Ready in 7.0s! Access with:

          ssh -p 52278 e1e-4575-testsshworks@localhost

          exe.dev ▶
  --- FAIL: TestSSHWorks (12.87s)
      box_management_test.go:29: want "e1e-4575-testsshworks.*\\$" match in output (read |0: i/o timeout). actual output:
          Warning: Permanently added '[localhost]:52278' (ED25519) to the list of known hosts.
          exe.dev ▶

Where an attempt to create a machine named "testscpworks" actually
got a machine called "testsshworks" from a parallel test.